### PR TITLE
Use unified logging instead of syslog on iOS 13+

### PR DESCRIPTION
**Pull request by jmagman**
Use os_log instead of syslog.

Fixes https://github.com/flutter/flutter/issues/44030.

See also:
https://github.com/flutter/engine/pull/3797
https://github.com/flutter/engine/pull/3739
https://github.com/flutter/engine/pull/3728
https://github.com/flutter/engine/pull/3726
https://github.com/flutter/engine/pull/3484
https://github.com/flutter/engine/pull/3481

### CODE REVIEW

File: fml/logging.cc [hunk 1]
```diff
@@ -63,6 +64,9 @@ LogMessage::LogMessage(LogSeverity severity,
 LogMessage::~LogMessage() {
   stream_ << std::endl;
 
+  const auto log_string = stream_.str();
+  const char* chars = log_string.c_str();
```
Comment (cbracken) [inline fml/logging.cc]:
```
../../flutter/fml/logging.cc:68:15: error: unused variable 'chars' [-Werror,-Wunused-variable]
```

Comment (jmagman) [reply fml/logging.cc]: Dang it I thought I fixed that. Thanks for catching.

File: fml/logging.cc [hunk 2]
```diff
@@ -80,9 +84,35 @@ LogMessage::~LogMessage() {
...
+  // Unified logging (os_log) became available in iOS 9.0 and syslog stopped working in iOS 13.0.
+  // idevicesyslog made device syslog available on the connected host, but there is
+  // no known API to view device unified logging on the host.
+  // Flutter tool will continue to observe syslog on devices older than iOS 13.0 since it
+  // provides more logging context, particularly for application crashes.
+  if (__builtin_available(iOS 13.0, macOS 10.11, *)) {
+    static os_log_t engineLog = os_log_create("io.flutter", "engine");
+    switch (severity_) {
+      // LogSeverity LOG_INFO and LOG_WARNING collide with syslog log level macros.
+      case 0 /* LOG_INFO */:
```
Comment (chinmaygarde) [inline fml/logging.cc]: Please file a bug for us to prefix these macros with `FML_` so we are no longer susceptible to such collisions. Cross referencing that bug with a TODO here would be great. Thanks.

File: fml/logging.cc [hunk 3]
```diff
@@ -80,9 +84,35 @@ LogMessage::~LogMessage() {
       priority = ANDROID_LOG_FATAL;
       break;
   }
-  __android_log_write(priority, "flutter", stream_.str().c_str());
-#elif defined(OS_IOS)
-  syslog(LOG_ALERT, "%s", stream_.str().c_str());
+  __android_log_write(priority, "flutter", chars);
+#elif defined(__APPLE__)
```
Comment (chinmaygarde) [inline fml/logging.cc]: Please stick to the macros in `build_config.h`. `OS_MACOSX` covers both iOS and MacOS so that may be used here instead of depending on a macro we don't control.

File: lib/ui/dart_runtime_hooks.cc [hunk 4]
```diff
@@ -199,19 +200,28 @@ void Logger_PrintString(Dart_NativeArguments args) {
...
-    syslog(1 /* LOG_ALERT */, "%.*s", (int)length, chars);
+    //
+    // Unified logging (os_log) became available in iOS 9.0 and syslog stopped working in iOS 13.0.
+    // idevicesyslog made device syslog available on the connected host, but there is
+    // no known API to view device unified logging on the host.
+    // Flutter tool will continue to observe syslog on devices older than iOS 13.0 since it
+    // provides more logging context, particularly for application crashes.
+    if (__builtin_available(iOS 13.0, macOS 10.11, *)) {
+      static os_log_t dart_log = os_log_create("io.flutter", "dart");
+      os_log(dart_log, "%.*s", (int)length, chars);
```
Comment (chinmaygarde) [inline lib/ui/dart_runtime_hooks.cc]: Please avoid C style casts in C++ TU's (I realize the old code ignored this guidance).

File: lib/ui/dart_runtime_hooks.cc [hunk 5]
```diff
@@ -30,7 +30,8 @@
 
 #if defined(OS_ANDROID)
 #include <android/log.h>
-#elif defined(OS_IOS)
+#elif defined(__APPLE__)
```
Comment (chinmaygarde) [inline lib/ui/dart_runtime_hooks.cc]: Ditto about using Macros we don't control. Here and elsewhere.

File: fml/logging.cc [hunk 6]
```diff
@@ -80,9 +84,35 @@ LogMessage::~LogMessage() {
...
+  // Unified logging (os_log) became available in iOS 9.0 and syslog stopped working in iOS 13.0.
+  // idevicesyslog made device syslog available on the connected host, but there is
+  // no known API to view device unified logging on the host.
+  // Flutter tool will continue to observe syslog on devices older than iOS 13.0 since it
+  // provides more logging context, particularly for application crashes.
+  if (__builtin_available(iOS 13.0, macOS 10.11, *)) {
+    static os_log_t engineLog = os_log_create("io.flutter", "engine");
```
Comment (chinmaygarde) [inline fml/logging.cc]: Please follow the style guide on naming variables. go/fluttercpp#Variable_Names

**Comment by cbracken** [comment]
@jmagman ping for followup on @chinmaygarde 's comments. Other than those, this should be ready to go.

File: lib/ui/dart_runtime_hooks.cc [hunk 7]
```diff
@@ -199,19 +200,29 @@ void Logger_PrintString(Dart_NativeArguments args) {
...
+    //
+    // Unified logging (os_log) became available in iOS 9.0 and syslog stopped
+    // working in iOS 13.0. idevicesyslog made device syslog available on the
+    // connected host, but there is no known API to view device unified logging
+    // on the host. Flutter tool will continue to observe syslog on devices
+    // older than iOS 13.0 since it provides more logging context, particularly
+    // for application crashes.
+    if (__builtin_available(iOS 13.0, macOS 10.11, *)) {
+      os_log_t dart_log = os_log_create("io.flutter", "dart");
+      os_log(dart_log, "%.*s", @(length).intValue, chars);
```
Comment (jmagman) [inline lib/ui/dart_runtime_hooks.cc]: @chinmaygarde 
> Please avoid C style casts in C++ TU's (I realize the old code ignored this guidance).

I created a NSNumber to avoid the cast but that seems overkill. The `%.*` needs to be an int, I don't see a way to pass an unsigned long as a width specifier.

Comment (cbracken) [reply lib/ui/dart_runtime_hooks.cc]: Use a C++ style `static_cast<int>(length)` here instead.
