### PR TITLE
Roll dart to c080951d45e79cd25df98036c4be835b284a269c.

### PR DESCRIPTION
**Pull request by aam**
Changes since last roll:
```
c080951d45 [build] Declare dependency of the version strings on the current Git commit.
693390a776 Index and search implicit references to optional positional parameters.
80a571d546 Take the --preview-dart-2 defaults from the context and options classes, not the cli tool defaults. Also, allow --no-preview-dart-2 from dartanalyzer.
8d47a6e86f Add a fix for lints that recommend using final (issue 32473)
0b48112d3e Fix nsm forwarding bug
977f4c706f Issue 32397. Fix for top-level inference and implicit creation.
b8093e3323 Generate signature of instantiated generic function from uninstantiated function
528d9d2e1f Do not hint when only a responsive asset exists (issue 32250)
5eb6d980b5 Do not hint when using a deprecated parameter in the defining function (issue 32468)
aff70cafc1 [vm] Fix reading of Object::extractor_parameter_types() from a snapshot
23fccf2e59 [VM] ARM64 unboxed 64 bit fix signed/unsigned const shift
e66733dd60 Simplify test case bug32353_test and decouple it from dart:io
e067f7fdfa The dart-dfe target is no longer being benchmarked.
7ce30c5289 Fix status files after 26e689de05b4
978840a42f [infra] Use a jessie sysroot for sanitizer builds
ad62702e93 Update status
11c77930e0 [infra] Turn on C++14 in the compiler config
30a87ce3fa [VM] ARM64: Add unboxed 64 bit integers
d2b7787186 [infra] Use downloaded sysroots by default
76b8e397ed Revert "Reland "[VM runtime] Switch intrinsics from old to new Bigint implementation.""
26e689de05 More work on signatures
5f51db3efb More status preparations to make the CQ clean
2cb80620bd Revert "[vm/simarm] Fix VRECPS/VRSQRTSQS instruction implementation."
feac6cfc20 Deal with Function type parameter contexts in closure conversion.
76a672e8ea mark lib_2/html/fileapi_entry_test flaky on ddc+mac
97bbe2f20b [vm] Avoid using objects in VM isolate heap for de-duplication
e1909cb52a Update Outline protocol - change offset/length, add codeOffset/codeLength.
602a8c2a7b Clean up usage of deprecated constants
5c94ec7b43 avoid generating unused constructors in dart:html
7aa3e54acf [vm] Fix computation of hashCode of a closure with null receiver
b93c74092a Make isInterceptedCall a field
c956cc152f Prepare co19 for d8-hostchecked-dart2js-with-cfe.
4c881188b2 Disable the .whereType method until generic methods are turned on.
16e8194147 Prepare additional lib, html, samples statuses: this embeds of d8-hostcheck results
0013f6acf8 Prepare co19 for the FE switch
22ccad1aa6 [vm] Stream writing snapshots as assembly to reduce peak memory usage.
eea08cfabe Add optional 'file' for getElementDeclarations.
b7cb8a1daa Mark 2 more tests as flaky
8240134d66 [infra] Roll boringssl forward. Use clang for arm on Linux.
e775ae9c30 Mark flaky co19 test
3da9c349d4 [vm/simarm] Fix VRECPS/VRSQRTSQS instruction implementation.
d059e97974 Add platform.dill files to the hostchecked try bots.
b3c12d4e3a Dart 2 Libraries Wave 3
021a29d68f Move analyzer-specific status lines into language_2_analyzer.status
b457d71713 Canonicalize representation of a message without location.
383517d292 [VM runtime] Fix type canonicalization (fixes #32425). A reused type argument vector that is longer than necessary needs to be shortened to the correct length upon type canonicalization. The runtime call comparing two instance runtime types also needs to consider reused vectors. Add regression test.
0fdbc331f6 Fix dynamic type dependencies in codegen
ef5909b986 Remove now unused dartk_wrappers
50ba330a04 Fix for suggesting both class and its default constructor.
e3ecc87eb9 [VM / Kernel ] Fixed issue where enum classes were not being marked as such in the VM. Enum class fields are now eagerly initialized.
4c58384b50 Prepare html, isolate, lib, and lib_2 status files to turn on CFE on dart2js by default
24507da9da Fix stack overflow when analyzing type variables in generic methods.
0e30facfc3 Update versions of the following packages to the latest versions - boolean_selector - collection
211bf1ee5f [vm/kernel/aot] Cache specializations of cone types in TFA
1c8841e52a [vm/kernel/aot] Fully support named parameters in type flow analysis
618cd897e6 Gardening: Adjust test status to fix bots again. Didn't fix the right status file last time and I couldn't test this since it's on Windows. :-(
23a7b62c42 Use type of receiver for setter target identification
f5b5ae86b6 Respect comments when inserting imports (issue 32432)
7290c950d0 Change name of 'signature' to ':signature' to not conflict with a DOM member.
7f9d5d318a Gardening: Change test status for standalone_2/namespace_test on Windows. Has been passing for as far back as I can see in the history.
55f7687908 [infra] Enable front end CQ builder
e8018bfdea Mark tests as flaky
9d17f3a92d Tests no longer crash
90c08d5287 Update co19 status for Chrome 65 roll
440b58d644 Start running analyzer tests with --preview-dart-2.
dc0f4c840c Fix status of map_literal1_test on analyzer
aecf5bf56e [VM] Remove locking in code called by signal handler, ensure profiler thread sees valid [Redirection] list
a55cdaee08 A bit of gardening
db08061424 Handle implicit tear-off of .call when an implicit downcast is required
8f4db274f1 Compute which selectors that need type arguments
83c8c21abe Gracefully handle local function modifiers
8831dd1308 Remove failing assertion
a3218d0b72 Roll back change to pkg/dev_compiler/analysis_options.yaml
50a6bb559d Update co19 status on IE11 after co19 update
6b91b4f2d2 Remove RuntimeTypesNeed.classUsesTypeVariableLiteral
f69da8e36b Move tests to /model/
d17db1d5f3 Pass type inference context down to field initializer when type inferred via override
675048d0b6 Add pragma class to dart:core.
94aa20dd07 Update status for $compiler == fasta
615f40bc1d Ensure that `null` is not used as a context in more places.
f3687198b8 Update dart2js_extra: normalize further and update to match runtime==chrome expectations
18aa6b570f Delete recursive import test, improve comment of dummy_compiler_test.
7fe8bdb2ee Refactor tests
932a99a731 Prepare pkg.status to enable dart2js CFE by default
dab7da78cd fix implicit casts in DDC
1b9b3453de fix DDC ES6 module export names, part of #32272
69f8d4ef0d Fix parsing of super expressions (issue 32393)
2ace7c9e9a Update dart2js-minified status for co19 no-such-method test
a1cacec5fc Update status after co19 roll
6b44182344 Only widgets in libraries can be rendered.
8d6b050e28 [VM] Guard against duplicate entries in the static [Redirection::list_]
be87175fee Implement Flutter Outline rendering API.
619434d38d Remember that C() is a compile-time constant expression.
18fe31ab11 Remove useOptimizedMixins from dart2js
9f56e28372 Mixin Applications with a Vengeance
3f71dc5dd2 Add preview_dart_2 to supported set of status file variables
bda78a0f41 Deprecated old upper-case constants.
```

### CODE REVIEW

**Comment by jason-simmons** [comment]
The framework isn't running in --preview-dart-2 mode with this version of Dart due to an issue with mixins.

The error was introduced in https://github.com/dart-lang/sdk/commit/9f56e283721ce7809f028680133484a6b24f9202

Stack trace from running Gallery:
```
══╡ EXCEPTION CAUGHT BY WIDGETS LIBRARY ╞═══════════════════════════════════════════════════════════
The following NoSuchMethodError was thrown building
_OverlayEntry-[LabeledGlobalKey<_OverlayEntryState>#bb499](state: _OverlayEntryState#a91e9):
Class 'RenderStack' has no instance setter '_firstChild'.
Receiver: Instance of 'RenderStack'
Tried calling: _firstChildInstance of 'RenderIgnorePointer'
 When the exception was thrown, this was the stack:
 #0      Object.noSuchMethod (dart:core/object_patch.dart:46:5)
 #1      _RenderStack&RenderBox&ContainerRenderObjectMixin._insertIntoChildList (package:flutter/src/rendering/object.dart:2727:7)
 #2      _RenderStack&RenderBox&ContainerRenderObjectMixin.insert (package:flutter/src/rendering/object.dart:2766:5)
 #3      MultiChildRenderObjectElement.insertChildRenderObject (package:flutter/src/widgets/framework.dart:4697:18)
 #4      RenderObjectElement.attachRenderObject (package:flutter/src/widgets/framework.dart:4492:35)
 #5      RenderObjectElement.mount (package:flutter/src/widgets/framework.dart:4262:5)
...
```

**Comment by aam** [comment]
Thanks for the heads up, @jason-simmons ! I reverted the roll and created https://github.com/flutter/flutter/issues/15368 to track the regression.
